steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["get", "-v", "github.com/gabriel/grpcutil/protoc-gen-tstypes"]
    env: ["PROJECT_ROOT=github.com/gabriel/grpcutil"]

  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/gabriel/grpcutil/protoc-gen-tstypes"]
    env: ["PROJECT_ROOT=github.com/gabriel/grpcutil"]
